apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: payment-app

  namespaceSelector:
    matchNames:
      - payments

  endpoints:
    - port: http
      path: /metrics
      interval: 15s